CREATE USER 'dati'@'localhost' IDENTIFIED BY 'dati';

CREATE DATABASE bd2_tours_1;


GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP,
    INDEX, ALTER ON bd2_tours_1.* TO 'dati'@'localhost';

FLUSH PRIVILEGES;